spring:
  application:
    name: "viki-university"
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false"
  jpa:
    show-sql: true
    defer-datasource-initialization: true # Without this script in data.sql won't execute
    hibernate:
      ddl-auto: "update" # This creates / updates tables

server:
  port: 8443
  ssl:
    key-store: classpath:vpk_keystore.jks
    key-store-password: password123
    key-store-type: JKS
    key-alias: vpkalias